#define TL    " ┌"
#define TR    "┐"
#define BL    " └"
#define BR    "┘"
#define VL    " │"
#define VR    "│ "
#define MD    "┬"
#define MU    "┴"
#define MVL    "├"
#define MVR    "┤"
#define MMM    "┼"
#define LINE  "───────────────────────────────────"
#define CLEARLINE "0K"